Add librca util function to calculate percentiles
Telecominfraproject/wlan-cloud-rrm pull request #115
Opened 2022-11-01 02:51 UTC by RockyMandayam2

Add librca util function to calculate percentiles.

2022-11-01 15:34 UTC, jwoos requested changes
please remove all the extra files!

2022-11-01 15:34 UTC, jwoos commented on lib-rca/src/test/java/com/facebook/openwifi/librca/UtilsTest.java
> +		assertTrue(actual == exp1 || actual == exp2);
Does this not have a consistent behavior?

2022-11-01 17:39 UTC, paulvarkey requested changes
Was deletion of RootCauseAnalyzerTest.java intentional?

The test seems it ought to be deterministic -- so I second jwoos's comment.

2022-11-01 22:53 UTC, zhiqiand commented on lib-rca/src/test/java/com/facebook/openwifi/librca/UtilsTest.java
> +		actual = Utils.getValueAtPercentile(values, 99.9);
Can you test a 10th/ 90th percentile? That's the only two use cases in RCA.

2022-11-02 16:07 UTC, closed without merging

2022-11-02 16:10 UTC, RockyMandayam2 commented
Closed this PR. Will open a new one using an apache library to do the calculations